# Generated by Django 3.2.8 on 2021-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='aliads',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
