# Generated by Django 3.2.8 on 2021-10-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_aliads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='aliads',
            new_name='alias',
        ),
    ]
