# Generated by Django 3.2.8 on 2021-10-28 15:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cartorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desc_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
