# Generated by Django 3.2.8 on 2021-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
