version: '3.5'
services: 
    django:
        build: .
        restart: always
        ports:
            - 8001:8080
        working_dir: /app
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - ./shop:/app       